AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  data-processor
  SAM Template for data-processor app

Parameters:
  MysqlUser:
    Type: String
    Default: ascend
  MysqlPassword:
    Type: String
  MysqlDbName:
    Type: String
    Default: ascend_data
  MysqlPort:
    Type: String
    Default: 3306

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 512

Resources:
  DataBucket:
    Type: AWS::S3::Bucket
    # Properties:
  DataBase:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      AutoMinorVersionUpgrade: true
      DBInstanceClass: db.t3.micro
      DBName: !Ref MysqlDbName
      Engine: mysql
      # EngineVersion: 8.0.36
      Port: !Ref MysqlPort
      MasterUsername: !Ref MysqlUser
      MasterUserPassword: !Ref MysqlPassword
      MaxAllocatedStorage: 30
      MultiAZ: false
      PubliclyAccessible: false
      # StorageType: gp2
      # Tags:
      #   - Tag
      VPCSecurityGroups:
        - sg-03bbbc0242f0af41b

  DataProcessorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    DependsOn:
    Properties:
      CodeUri: data_processor/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Policies:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      Environment:
        Variables:
          MYSQL_USER: !Ref MysqlUser
          MYSQL_PASSWORD: !Ref MysqlPassword
          MYSQL_ENDPOINT: !GetAtt DataBase.Endpoint.Address
          MYSQL_PORT: !Ref MysqlPort
          DB_NAME: !Ref MysqlDbName
          ANSI_ENCODING: "cp1252"
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref DataBucket
            Events: s3:ObjectCreated:*
